### ISSUE TITLE
Navigation bar

### ISSUE THREAD

**Issue by tsolmonbat-batbold** [elija-lambourne/AiSignLanguage#29]
Navigation bar has functionality + design like shown in the mock-up. Navbar needs to be accessible from everywhere.
expected time: 2,5h

**Comment by elija-lambourne** [comment]
Update: almost done, missing nav functionality

**Comment by elija-lambourne** [comment]
DoD: The Navbar looks like it does in the mockups and can navigate you between the pages that are shown in the Navbar.
+ Has to be accesible (navigatable through screen readers and mobiel devices)
